from enum import Enum

class ReturnReasonCode(str, Enum):
    DEFECTIVE = "DEFECTIVE"
    WRONG_ITEM_RECEIVED = "WRONG_ITEM_RECEIVED"
    NOT_AS_DESCRIBED = "NOT_AS_DESCRIBED"
    NO_LONGER_NEEDED = "NO_LONGER_NEEDED"
    DAMAGED_IN_TRANSIT = "DAMAGED_IN_TRANSIT"
    MISSING_PARTS = "MISSING_PARTS"
    POOR_QUALITY = "POOR_QUALITY"
    ARRIVED_LATE = "ARRIVED_LATE"
    OTHER = "OTHER"

class AdminResolutionAction(str, Enum):
    REFUND_APPROVED = "REFUND_APPROVED" # 买家获得退款，流程结束
    RETURN_DECLINED_BY_ADMIN = "RETURN_DECLINED_BY_ADMIN" # 管理员拒绝退货/退款，流程结束
    PARTIAL_REFUND_OFFERED = "PARTIAL_REFUND_OFFERED" # 管理员提议部分退款
    SELLER_FAULT_FULL_REFUND = "SELLER_FAULT_FULL_REFUND" # 卖家责任，全额退款
    BUYER_FAULT_CLOSED = "BUYER_FAULT_CLOSED" # 买家责任，关闭请求
    NEGOTIATED_SETTLEMENT = "NEGOTIATED_SETTLEMENT" # 协商解决
    # 可以根据需要添加更多具体操作

# 可以添加其他应用全局的枚举类型在这里 